/*
 * Methods
 *
 * This API exposes detectors for sensitive data in arbitrary string payloads.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ScanResponseLocationByteRange struct for ScanResponseLocationByteRange
type ScanResponseLocationByteRange struct {
	// the index of the fragment's starting byte
	Start int32 `json:"start,omitempty"`
	// the index of the fragment's ending byte
	End int32 `json:"end,omitempty"`
}
