/*
 * Methods
 *
 * This API exposes detectors for sensitive data in arbitrary string payloads.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ScanResponseConfidence struct for ScanResponseConfidence
type ScanResponseConfidence struct {
	// the predicted likelihood the fragment contains the indicated data type
	Bucket string `json:"bucket,omitempty"`
}
